export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    SIGNUP_TYPE: 'USER_SIGNUP_CHOICE',
    SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

    LOGOUT: 'USERS_LOGOUT',
};

export const jobConstants = {
    POSTING_SUCCESS: 'JOB_POSTING_SUCCESS',
    POSTING_FAILURE: 'JOB_POSTING_FAILURE'
}

export const httpParamConstants = {
    USER_EMPLOYER: 'employer',
    USER_JOBSEEKER: 'jobseeker'
}